export const theme = {
  colors: {
    background: "#FFFFFF",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    muted: "#F2F2F7",
    mutedForeground: "#8E8E93",
    border: "#E5E5EA",
    primary: "#4A90D9",
    primaryForeground: "#FFFFFF",
    primaryMuted: "#E8F0FE",
    secondary: "#F2F2F7",
    secondaryForeground: "#1C1C1E",
    destructive: "#FF3B30",
    destructiveMuted: "#FFF0F0",
    ring: "#4A90D9",
    // Chat bubbles
    userBubble: "#4A90D9",
    userBubbleText: "#FFFFFF",
    aiBubble: "#F2F2F7",
    kimiBubble: "#F3E5F5",
    circuitBubble: "#FFF3E0",
    headerBg: "#FFFFFF",
    headerText: "#1C1C1E",
    inputBg: "#F2F2F7",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 10,
    xl: 14,
    xxl: 18,
    full: 999,
  },
  fontSize: {
    xs: 11,
    sm: 13,
    base: 15,
    lg: 17,
    xl: 20,
    xxl: 24,
  },
  fontWeight: {
    normal: "400" as const,
    medium: "500" as const,
    semibold: "600" as const,
    bold: "700" as const,
  },
  shadow: {
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
  },
} as const;

export type Theme = typeof theme;
